name: Build and Test iCatcher+
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      # test

      - name: Build project
        run: |
          python -m pip install ".[dev]"

      - name: Restore cached models
        uses: actions/cache@v2
        with:
          path: reproduce/models/
          key: ${{ runner.os }}-models-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-models-${{ env.cache-name }}
            ${{ runner.os }}-models-
            ${{ runner.os }}-

      - name: Run tests
        run:  python -m pytest tests
        # if running out of memory in future, add markers in future
        # might want to have an action slow at some point if things are slow

      - name: Cache models
        uses: actions/cache@v2
        with:
          path: reproduce/models/
          key: ${{ runner.os }}-models-${{ env.cache-name }}
